### PR TITLE
Fix selection issues

### LINKED ISSUE #5: phrase tags added to empty text nodes
When splitting a parent phrase, there can be an empty text node before or after the selection. In this case, the phrase tags should not be added to the empty text node.

### PR DESCRIPTION
**Pull request by cruzanmo**
Fixes #5 and #4

### CODE REVIEW

File: src/medium-editor-phrase.js [hunk 1]
```diff
@@ -182,8 +220,8 @@
 
       // select a text node where the original selection needs to be re-inserted
       selection.removeAllRanges();
-      placeholderEl = ancestorPhraseParent.querySelector(this.placeholderSelector);
-      textNodePlaceholder = placeholderEl.parentNode.insertBefore(this.document.createTextNode('safariNeedsTextNode'), placeholderEl.nextSibling);
+      placeholderEl = ancestorPhraseParent.querySelector(placeholderSelector);
+      textNodePlaceholder = this.insertTextNodePlaceholderAfter(placeholderEl);
```
Comment (davidandrewfrey) [inline src/medium-editor-phrase.js]: Nice!

**Comment by davidandrewfrey** [comment]
⭐ ⭐ ⭐ ⭐ ⭐
